package com.foshan.messageWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-18T01:23:51.140+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceSoap {

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(operationName = "mdSmsSend_u", action = "http://tempuri.org/mdSmsSend_u")
    @RequestWrapper(localName = "mdSmsSend_u", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSendU")
    @ResponseWrapper(localName = "mdSmsSend_uResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSendUResponse")
    @WebResult(name = "mdSmsSend_uResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdSmsSendU(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 彩信接收：sn软件序列号;pwd加密密码md5(sn+password).返回:彩信内容
     */
    @WebMethod(action = "http://tempuri.org/mdMmsReceive")
    @RequestWrapper(localName = "mdMmsReceive", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsReceive")
    @ResponseWrapper(localName = "mdMmsReceiveResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsReceiveResponse")
    @WebResult(name = "mdMmsReceiveResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdMmsReceive(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 发送短信：userId软件序列号;password加密密码md5(sn+password);pszMobis手机号列表，以逗号,隔开;pszMsg发送内容utf-8编码;iMobiCount手机号数量;pszSubPort扩展子号.返回:唯一标识
     */
    @WebMethod(operationName = "MongateCsSpSendSmsNew", action = "http://tempuri.org/MongateCsSpSendSmsNew")
    @RequestWrapper(localName = "MongateCsSpSendSmsNew", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MongateCsSpSendSmsNew")
    @ResponseWrapper(localName = "MongateCsSpSendSmsNewResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MongateCsSpSendSmsNewResponse")
    @WebResult(name = "MongateCsSpSendSmsNewResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mongateCsSpSendSmsNew(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "pszMobis", targetNamespace = "http://tempuri.org/")
        java.lang.String pszMobis,
        @WebParam(name = "pszMsg", targetNamespace = "http://tempuri.org/")
        java.lang.String pszMsg,
        @WebParam(name = "iMobiCount", targetNamespace = "http://tempuri.org/")
        int iMobiCount,
        @WebParam(name = "pszSubPort", targetNamespace = "http://tempuri.org/")
        java.lang.String pszSubPort
    );

    /**
     * 接收短信：sn软件序列号;pwd序列号密码。total_num为负数，表示操作失败
     */
    @WebMethod(operationName = "RECSMS", action = "http://tempuri.org/RECSMS")
    @RequestWrapper(localName = "RECSMS", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.RECSMS")
    @ResponseWrapper(localName = "RECSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.RECSMSResponse")
    @WebResult(name = "RECSMSResult", targetNamespace = "http://tempuri.org/")
    public com.foshan.messageWS.ArrayOfMOBody recsms(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 查询余额：sn软件序列号;pwd加密密码md5(sn+password)
     */
    @WebMethod(action = "http://tempuri.org/balance")
    @RequestWrapper(localName = "balance", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Balance")
    @ResponseWrapper(localName = "balanceResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.BalanceResponse")
    @WebResult(name = "balanceResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String balance(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 获取软件序列号状态：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "GetStatus", action = "http://tempuri.org/GetStatus")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetStatusResponse")
    @WebResult(name = "GetStatusResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getStatus(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 语音发送：sn软件序列号;pwd加密密码md5(sn+password);title语音主题;mobile手机号码,以英文逗号隔开,为空表示语音合成请求;txt文本内容;content文件内容,base64编码(wav文件名,文件base64编码串);srcnumber源号码;stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod(action = "http://tempuri.org/mdAudioSend")
    @RequestWrapper(localName = "mdAudioSend", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdAudioSend")
    @ResponseWrapper(localName = "mdAudioSendResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdAudioSendResponse")
    @WebResult(name = "mdAudioSendResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdAudioSend(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "txt", targetNamespace = "http://tempuri.org/")
        java.lang.String txt,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "srcnumber", targetNamespace = "http://tempuri.org/")
        java.lang.String srcnumber,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime
    );

    /**
     * 彩信文件传输：sn软件序列号;pwd加密密码md5(sn+password);rrid第一个接口返回id;content内容,base64编码.返回:rrid
     */
    @WebMethod(action = "http://tempuri.org/mmsFileMT")
    @RequestWrapper(localName = "mmsFileMT", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MmsFileMT")
    @ResponseWrapper(localName = "mmsFileMTResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MmsFileMTResponse")
    @WebResult(name = "mmsFileMTResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mmsFileMT(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(operationName = "mdSmsSend_DES", action = "http://tempuri.org/mdSmsSend_DES")
    @RequestWrapper(localName = "mdSmsSend_DES", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSendDES")
    @ResponseWrapper(localName = "mdSmsSend_DESResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSendDESResponse")
    @WebResult(name = "mdSmsSend_DESResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdSmsSendDES(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 更改密码：sn软件序列号;pwd序列号密码;newpwd新密码
     */
    @WebMethod(operationName = "UDPPwd", action = "http://tempuri.org/UDPPwd")
    @RequestWrapper(localName = "UDPPwd", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.UDPPwd")
    @ResponseWrapper(localName = "UDPPwdResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.UDPPwdResponse")
    @WebResult(name = "UDPPwdResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String udpPwd(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "newpwd", targetNamespace = "http://tempuri.org/")
        java.lang.String newpwd
    );

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);title彩信主题;mobile手机号码,以英文逗号隔开;content内容,base64编码(文件名1,文件base64编码串;文件名2,文件base64编码串);stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod(action = "http://tempuri.org/mdMmsSend")
    @RequestWrapper(localName = "mdMmsSend", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsSend")
    @ResponseWrapper(localName = "mdMmsSendResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsSendResponse")
    @WebResult(name = "mdMmsSendResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdMmsSend(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime
    );

    /**
     * 回执：sn软件序列号;pwd加密密码md5(sn+password);maxid最大id
     */
    @WebMethod(action = "http://tempuri.org/report2DES")
    @RequestWrapper(localName = "report2DES", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Report2DES")
    @ResponseWrapper(localName = "report2DESResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Report2DESResponse")
    @WebResult(name = "report2DESResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String report2DES(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "maxid", targetNamespace = "http://tempuri.org/")
        long maxid,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 回执：sn软件序列号;password加密密码md5(sn+password)
     */
    @WebMethod(operationName = "MongateCsGetStatusReportExEx", action = "http://tempuri.org/MongateCsGetStatusReportExEx")
    @RequestWrapper(localName = "MongateCsGetStatusReportExEx", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MongateCsGetStatusReportExEx")
    @ResponseWrapper(localName = "MongateCsGetStatusReportExExResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MongateCsGetStatusReportExExResponse")
    @WebResult(name = "MongateCsGetStatusReportExExResult", targetNamespace = "http://tempuri.org/")
    public com.foshan.messageWS.ArrayOfString mongateCsGetStatusReportExEx(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);title彩信主题;mobile手机号码,以英文逗号隔开;content内容,base64编码(文件名1,文件base64编码串utf8;文件名2,文件base64编码串utf8);stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod(operationName = "mdMmsSend_uex", action = "http://tempuri.org/mdMmsSend_uex")
    @RequestWrapper(localName = "mdMmsSend_uex", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsSendUex")
    @ResponseWrapper(localName = "mdMmsSend_uexResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsSendUexResponse")
    @WebResult(name = "mdMmsSend_uexResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdMmsSendUex(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext
    );

    /**
     * 接收短信：sn软件序列号;pwd加密密码md5(sn+password).[优先使用本接口]
     */
    @WebMethod(action = "http://tempuri.org/mo")
    @RequestWrapper(localName = "mo", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Mo")
    @ResponseWrapper(localName = "moResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MoResponse")
    @WebResult(name = "moResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mo(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号码,以英文逗号隔开;content内容,base64编码(zip文件base64编码串);stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod(action = "http://tempuri.org/mdMmsSendF")
    @RequestWrapper(localName = "mdMmsSendF", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsSendF")
    @ResponseWrapper(localName = "mdMmsSendFResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsSendFResponse")
    @WebResult(name = "mdMmsSendFResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdMmsSendF(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime
    );

    /**
     * 获取余额：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "GetBalance", action = "http://tempuri.org/GetBalance")
    @RequestWrapper(localName = "GetBalance", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetBalance")
    @ResponseWrapper(localName = "GetBalanceResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetBalanceResponse")
    @WebResult(name = "GetBalanceResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getBalance(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(operationName = "mdSmsSend_g", action = "http://tempuri.org/mdSmsSend_g")
    @RequestWrapper(localName = "mdSmsSend_g", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSendG")
    @ResponseWrapper(localName = "mdSmsSend_gResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSendGResponse")
    @WebResult(name = "mdSmsSend_gResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdSmsSendG(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(action = "http://tempuri.org/mt")
    @RequestWrapper(localName = "mt", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Mt")
    @ResponseWrapper(localName = "mtResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MtResponse")
    @WebResult(name = "mtResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mt(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 设置高端发送：sn软件序列号;pwd序列号密码;gd参数1普通通道2高端通道;
     */
    @WebMethod(operationName = "SetGaoDuan", action = "http://tempuri.org/SetGaoDuan")
    @RequestWrapper(localName = "SetGaoDuan", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SetGaoDuan")
    @ResponseWrapper(localName = "SetGaoDuanResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SetGaoDuanResponse")
    @WebResult(name = "SetGaoDuanResult", targetNamespace = "http://tempuri.org/")
    public double setGaoDuan(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "gd", targetNamespace = "http://tempuri.org/")
        java.lang.String gd
    );

    /**
     * 文件传输：sn软件序列号;pwd加密密码md5(sn+password);fname增值文件名;rrid第一个接口返回id;sort批次;total总次数;ftype类别1短信2彩信3语音4传真5邮件;content内容,base64编码.返回:rrid
     */
    @WebMethod(action = "http://tempuri.org/fileMT")
    @RequestWrapper(localName = "fileMT", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.FileMT")
    @ResponseWrapper(localName = "fileMTResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.FileMTResponse")
    @WebResult(name = "fileMTResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String fileMT(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "fname", targetNamespace = "http://tempuri.org/")
        java.lang.String fname,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid,
        @WebParam(name = "sort", targetNamespace = "http://tempuri.org/")
        int sort,
        @WebParam(name = "total", targetNamespace = "http://tempuri.org/")
        int total,
        @WebParam(name = "ftype", targetNamespace = "http://tempuri.org/")
        int ftype,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );

    /**
     * 发送变量短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字;bcode变量编码.返回:唯一标识
     */
    @WebMethod(action = "http://tempuri.org/bianliang")
    @RequestWrapper(localName = "bianliang", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Bianliang")
    @ResponseWrapper(localName = "bianliangResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.BianliangResponse")
    @WebResult(name = "bianliangResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String bianliang(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid,
        @WebParam(name = "bcode", targetNamespace = "http://tempuri.org/")
        java.lang.String bcode
    );

    /**
     * 发送短信：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容
     */
    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SendSMSResponse")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSMS(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );

    /**
     * 通道测试：sn软件序列号;pwd序列号密码;mobile手机号列表，最多20个，以逗号,隔开
     */
    @WebMethod(operationName = "SMSTest", action = "http://tempuri.org/SMSTest")
    @RequestWrapper(localName = "SMSTest", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SMSTest")
    @ResponseWrapper(localName = "SMSTestResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SMSTestResponse")
    @WebResult(name = "SMSTestResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String smsTest(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile
    );

    /**
     * 更改签名（网络版）：sn软件序列号;pwd序列号密码;sign企业签名(2-15个字符);subcode最长9位数字扩展码;comName企业全称
     */
    @WebMethod(operationName = "UDPSIGNEX", action = "http://tempuri.org/UDPSIGNEX")
    @RequestWrapper(localName = "UDPSIGNEX", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.UDPSIGNEX")
    @ResponseWrapper(localName = "UDPSIGNEXResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.UDPSIGNEXResponse")
    @WebResult(name = "UDPSIGNEXResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String udpsignex(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign,
        @WebParam(name = "comName", targetNamespace = "http://tempuri.org/")
        java.lang.String comName
    );

    /**
     * 接收短信：sn软件序列号;pwd加密密码md5(sn+password);maxID：上次接收最大id
     */
    @WebMethod(action = "http://tempuri.org/mo2")
    @RequestWrapper(localName = "mo2", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Mo2")
    @ResponseWrapper(localName = "mo2Response", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Mo2Response")
    @WebResult(name = "mo2Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String mo2(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "maxID", targetNamespace = "http://tempuri.org/")
        int maxID
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(action = "http://tempuri.org/mdSmsSend")
    @RequestWrapper(localName = "mdSmsSend", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSend")
    @ResponseWrapper(localName = "mdSmsSendResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSendResponse")
    @WebResult(name = "mdSmsSendResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdSmsSend(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 更改签名：sn软件序列号;pwd序列号密码;sign企业签名(2-15个字符)
     */
    @WebMethod(operationName = "UDPSIGN", action = "http://tempuri.org/UDPSIGN")
    @RequestWrapper(localName = "UDPSIGN", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.UDPSIGN")
    @ResponseWrapper(localName = "UDPSIGNResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.UDPSIGNResponse")
    @WebResult(name = "UDPSIGNResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String udpsign(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign
    );

    /**
     * 获取高端发送：sn软件序列号;pwd序列号密码;
     */
    @WebMethod(operationName = "GetGaoDuan", action = "http://tempuri.org/GetGaoDuan")
    @RequestWrapper(localName = "GetGaoDuan", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetGaoDuan")
    @ResponseWrapper(localName = "GetGaoDuanResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetGaoDuanResponse")
    @WebResult(name = "GetGaoDuanResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getGaoDuan(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 获取软件序列号2参数：sn软件序列号;pwd序列号密码;
     */
    @WebMethod(operationName = "GetAllInfo2", action = "http://tempuri.org/GetAllInfo2")
    @RequestWrapper(localName = "GetAllInfo2", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetAllInfo2")
    @ResponseWrapper(localName = "GetAllInfo2Response", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetAllInfo2Response")
    @WebResult(name = "GetAllInfo2Result", targetNamespace = "http://tempuri.org/")
    public com.foshan.messageWS.RegistryInfo2 getAllInfo2(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "ver", targetNamespace = "http://tempuri.org/")
        java.lang.String ver,
        @WebParam(name = "oem", targetNamespace = "http://tempuri.org/")
        java.lang.String oem
    );

    /**
     * 回执：sn软件序列号;pwd加密密码md5(sn+password);maxid最大id
     */
    @WebMethod(action = "http://tempuri.org/report2")
    @RequestWrapper(localName = "report2", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Report2")
    @ResponseWrapper(localName = "report2Response", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Report2Response")
    @WebResult(name = "report2Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String report2(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "maxid", targetNamespace = "http://tempuri.org/")
        long maxid,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 编解码：content中文内容;code编解码类型;type，0编码1解码
     */
    @WebMethod(operationName = "TestCode", action = "http://tempuri.org/TestCode")
    @RequestWrapper(localName = "TestCode", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.TestCode")
    @ResponseWrapper(localName = "TestCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.TestCodeResponse")
    @WebResult(name = "TestCodeResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String testCode(
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        java.lang.String code,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        java.lang.String type
    );

    /**
     * 网络版接收短信utf-8编码：sn软件序列号;pwd序列号密码;subcode子号码。total_num为负数，表示操作失败
     */
    @WebMethod(operationName = "RECSMSEx_UTF8", action = "http://tempuri.org/RECSMSEx_UTF8")
    @RequestWrapper(localName = "RECSMSEx_UTF8", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.RECSMSExUTF8")
    @ResponseWrapper(localName = "RECSMSEx_UTF8Response", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.RECSMSExUTF8Response")
    @WebResult(name = "RECSMSEx_UTF8Result", targetNamespace = "http://tempuri.org/")
    public com.foshan.messageWS.ArrayOfMOBody recsmsExUTF8(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(operationName = "mdSmsSend_AES", action = "http://tempuri.org/mdSmsSend_AES")
    @RequestWrapper(localName = "mdSmsSend_AES", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSendAES")
    @ResponseWrapper(localName = "mdSmsSend_AESResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdSmsSendAESResponse")
    @WebResult(name = "mdSmsSend_AESResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdSmsSendAES(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 发送短信（可扩展）：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容;subcode最长9位数字扩展码;rrid唯一标识,全数字
     */
    @WebMethod(operationName = "SendSMSEx_R", action = "http://tempuri.org/SendSMSEx_R")
    @RequestWrapper(localName = "SendSMSEx_R", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SendSMSExR")
    @ResponseWrapper(localName = "SendSMSEx_RResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SendSMSExRResponse")
    @WebResult(name = "SendSMSEx_RResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSMSExR(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 接收短信：sn软件序列号;password加密密码md5(sn+password).
     */
    @WebMethod(operationName = "MongateCsGetSmsExEx", action = "http://tempuri.org/MongateCsGetSmsExEx")
    @RequestWrapper(localName = "MongateCsGetSmsExEx", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MongateCsGetSmsExEx")
    @ResponseWrapper(localName = "MongateCsGetSmsExExResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MongateCsGetSmsExExResponse")
    @WebResult(name = "MongateCsGetSmsExExResult", targetNamespace = "http://tempuri.org/")
    public com.foshan.messageWS.ArrayOfString mongateCsGetSmsExEx(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    /**
     * 获取特服号：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "GetCode", action = "http://tempuri.org/GetCode")
    @RequestWrapper(localName = "GetCode", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetCode")
    @ResponseWrapper(localName = "GetCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetCodeResponse")
    @WebResult(name = "GetCodeResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getCode(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 软件序列号注册：sn软件序列号;pwd序列号密码;province省;city城市;trade行业;entname企业名称;linkman联系人;phone联系电话;mobile移动电话;email邮件地址;fax传真;address地址;postcode邮政编码
     */
    @WebMethod(operationName = "Register", action = "http://tempuri.org/Register")
    @RequestWrapper(localName = "Register", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.RegisterResponse")
    @WebResult(name = "RegisterResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String register(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "province", targetNamespace = "http://tempuri.org/")
        java.lang.String province,
        @WebParam(name = "city", targetNamespace = "http://tempuri.org/")
        java.lang.String city,
        @WebParam(name = "trade", targetNamespace = "http://tempuri.org/")
        java.lang.String trade,
        @WebParam(name = "entname", targetNamespace = "http://tempuri.org/")
        java.lang.String entname,
        @WebParam(name = "linkman", targetNamespace = "http://tempuri.org/")
        java.lang.String linkman,
        @WebParam(name = "phone", targetNamespace = "http://tempuri.org/")
        java.lang.String phone,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(name = "fax", targetNamespace = "http://tempuri.org/")
        java.lang.String fax,
        @WebParam(name = "address", targetNamespace = "http://tempuri.org/")
        java.lang.String address,
        @WebParam(name = "postcode", targetNamespace = "http://tempuri.org/")
        java.lang.String postcode,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign
    );

    /**
     * 获取软件序列号子号码长度：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "GetFlag", action = "http://tempuri.org/GetFlag")
    @RequestWrapper(localName = "GetFlag", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetFlag")
    @ResponseWrapper(localName = "GetFlagResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetFlagResponse")
    @WebResult(name = "GetFlagResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getFlag(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 接收短信utf-8编码：sn软件序列号;pwd序列号密码。total_num为负数，表示操作失败
     */
    @WebMethod(operationName = "RECSMS_UTF8", action = "http://tempuri.org/RECSMS_UTF8")
    @RequestWrapper(localName = "RECSMS_UTF8", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.RECSMSUTF8")
    @ResponseWrapper(localName = "RECSMS_UTF8Response", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.RECSMSUTF8Response")
    @WebResult(name = "RECSMS_UTF8Result", targetNamespace = "http://tempuri.org/")
    public com.foshan.messageWS.ArrayOfMOBody recsmsUTF8(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 传真发送：sn软件序列号;pwd加密密码md5(sn+password);title传真主题;mobile接收号码,以英文逗号隔开;content文件内容,base64编码(wav文件名,文件base64编码串);srcnumber发送号码;stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod(action = "http://tempuri.org/mdFaxSend")
    @RequestWrapper(localName = "mdFaxSend", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdFaxSend")
    @ResponseWrapper(localName = "mdFaxSendResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdFaxSendResponse")
    @WebResult(name = "mdFaxSendResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdFaxSend(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "srcnumber", targetNamespace = "http://tempuri.org/")
        java.lang.String srcnumber,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime
    );

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);title彩信主题;mobile手机号码,以英文逗号隔开;content内容,base64编码(文件名1,文件base64编码串;文件名2,文件base64编码串);stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod(operationName = "mdMmsSend_ex", action = "http://tempuri.org/mdMmsSend_ex")
    @RequestWrapper(localName = "mdMmsSend_ex", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsSendEx")
    @ResponseWrapper(localName = "mdMmsSend_exResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MdMmsSendExResponse")
    @WebResult(name = "mdMmsSend_exResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String mdMmsSendEx(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext
    );

    /**
     * 回执：sn软件序列号;pwd加密密码md5(sn+password);maxid最大id
     */
    @WebMethod(action = "http://tempuri.org/report")
    @RequestWrapper(localName = "report", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Report")
    @ResponseWrapper(localName = "reportResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.ReportResponse")
    @WebResult(name = "reportResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String report(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "maxid", targetNamespace = "http://tempuri.org/")
        long maxid
    );

    /**
     * 注销：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "UnRegister", action = "http://tempuri.org/UnRegister")
    @RequestWrapper(localName = "UnRegister", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.UnRegister")
    @ResponseWrapper(localName = "UnRegisterResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.UnRegisterResponse")
    @WebResult(name = "UnRegisterResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String unRegister(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 获取软件序列号参数：sn软件序列号;pwd序列号密码;
     */
    @WebMethod(operationName = "GetAllInfo", action = "http://tempuri.org/GetAllInfo")
    @RequestWrapper(localName = "GetAllInfo", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetAllInfo")
    @ResponseWrapper(localName = "GetAllInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GetAllInfoResponse")
    @WebResult(name = "GetAllInfoResult", targetNamespace = "http://tempuri.org/")
    public com.foshan.messageWS.RegistryInfo getAllInfo(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 网络版接收短信：sn软件序列号;pwd序列号密码;subcode子号码。total_num为负数，表示操作失败
     */
    @WebMethod(operationName = "RECSMSEx", action = "http://tempuri.org/RECSMSEx")
    @RequestWrapper(localName = "RECSMSEx", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.RECSMSEx")
    @ResponseWrapper(localName = "RECSMSExResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.RECSMSExResponse")
    @WebResult(name = "RECSMSExResult", targetNamespace = "http://tempuri.org/")
    public com.foshan.messageWS.ArrayOfMOBody recsmsEx(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode
    );

    /**
     * 发送短信：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容;rrid唯一标识,全数字
     */
    @WebMethod(operationName = "SendSMS_R", action = "http://tempuri.org/SendSMS_R")
    @RequestWrapper(localName = "SendSMS_R", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SendSMSR")
    @ResponseWrapper(localName = "SendSMS_RResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SendSMSRResponse")
    @WebResult(name = "SendSMS_RResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSMSR(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 发送短信（可扩展）：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容;subcode最长9位数字扩展码
     */
    @WebMethod(operationName = "SendSMSEx", action = "http://tempuri.org/SendSMSEx")
    @RequestWrapper(localName = "SendSMSEx", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SendSMSEx")
    @ResponseWrapper(localName = "SendSMSExResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.SendSMSExResponse")
    @WebResult(name = "SendSMSExResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSMSEx(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode
    );

    /**
     * 充值：sn软件序列号;pwd序列号密码;cardno充值卡号;cardpwd充值卡密码
     */
    @WebMethod(operationName = "ChargUp", action = "http://tempuri.org/ChargUp")
    @RequestWrapper(localName = "ChargUp", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.ChargUp")
    @ResponseWrapper(localName = "ChargUpResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.ChargUpResponse")
    @WebResult(name = "ChargUpResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String chargUp(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "cardno", targetNamespace = "http://tempuri.org/")
        java.lang.String cardno,
        @WebParam(name = "cardpwd", targetNamespace = "http://tempuri.org/")
        java.lang.String cardpwd
    );

    /**
     * 获取信息ID：sn软件序列号;pwd加密密码md5(sn+password)
     */
    @WebMethod(action = "http://tempuri.org/msgid")
    @RequestWrapper(localName = "msgid", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Msgid")
    @ResponseWrapper(localName = "msgidResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.MsgidResponse")
    @WebResult(name = "msgidResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String msgid(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 个性短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容,GB2312编码,以逗号,隔开;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(action = "http://tempuri.org/gxmt")
    @RequestWrapper(localName = "gxmt", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.Gxmt")
    @ResponseWrapper(localName = "gxmtResponse", targetNamespace = "http://tempuri.org/", className = "com.foshan.messageWS.GxmtResponse")
    @WebResult(name = "gxmtResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String gxmt(
        @WebParam(name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );
}
