package com.foshan.messageWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-18T01:23:50.890+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebServiceHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebServiceHttpGet {

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(operationName = "mdSmsSend_u")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdSmsSendU(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 彩信接收：sn软件序列号;pwd加密密码md5(sn+password).返回:彩信内容
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdMmsReceive(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 发送短信：userId软件序列号;password加密密码md5(sn+password);pszMobis手机号列表，以逗号,隔开;pszMsg发送内容utf-8编码;iMobiCount手机号数量;pszSubPort扩展子号.返回:唯一标识
     */
    @WebMethod(operationName = "MongateCsSpSendSmsNew")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mongateCsSpSendSmsNew(
        @WebParam(partName = "userId", name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(partName = "pszMobis", name = "pszMobis", targetNamespace = "http://tempuri.org/")
        java.lang.String pszMobis,
        @WebParam(partName = "pszMsg", name = "pszMsg", targetNamespace = "http://tempuri.org/")
        java.lang.String pszMsg,
        @WebParam(partName = "iMobiCount", name = "iMobiCount", targetNamespace = "http://tempuri.org/")
        java.lang.String iMobiCount,
        @WebParam(partName = "pszSubPort", name = "pszSubPort", targetNamespace = "http://tempuri.org/")
        java.lang.String pszSubPort
    );

    /**
     * 接收短信：sn软件序列号;pwd序列号密码。total_num为负数，表示操作失败
     */
    @WebMethod(operationName = "RECSMS")
    @WebResult(name = "ArrayOfMOBody", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfMOBody recsms(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 查询余额：sn软件序列号;pwd加密密码md5(sn+password)
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String balance(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 获取软件序列号状态：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "GetStatus")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getStatus(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 语音发送：sn软件序列号;pwd加密密码md5(sn+password);title语音主题;mobile手机号码,以英文逗号隔开,为空表示语音合成请求;txt文本内容;content文件内容,base64编码(wav文件名,文件base64编码串);srcnumber源号码;stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdAudioSend(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "title", name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "txt", name = "txt", targetNamespace = "http://tempuri.org/")
        java.lang.String txt,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "srcnumber", name = "srcnumber", targetNamespace = "http://tempuri.org/")
        java.lang.String srcnumber,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime
    );

    /**
     * 彩信文件传输：sn软件序列号;pwd加密密码md5(sn+password);rrid第一个接口返回id;content内容,base64编码.返回:rrid
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mmsFileMT(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(operationName = "mdSmsSend_DES")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdSmsSendDES(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 更改密码：sn软件序列号;pwd序列号密码;newpwd新密码
     */
    @WebMethod(operationName = "UDPPwd")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String udpPwd(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "newpwd", name = "newpwd", targetNamespace = "http://tempuri.org/")
        java.lang.String newpwd
    );

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);title彩信主题;mobile手机号码,以英文逗号隔开;content内容,base64编码(文件名1,文件base64编码串;文件名2,文件base64编码串);stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdMmsSend(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "title", name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime
    );

    /**
     * 回执：sn软件序列号;pwd加密密码md5(sn+password);maxid最大id
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String report2DES(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "maxid", name = "maxid", targetNamespace = "http://tempuri.org/")
        java.lang.String maxid,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 回执：sn软件序列号;password加密密码md5(sn+password)
     */
    @WebMethod(operationName = "MongateCsGetStatusReportExEx")
    @WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfString mongateCsGetStatusReportExEx(
        @WebParam(partName = "userId", name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);title彩信主题;mobile手机号码,以英文逗号隔开;content内容,base64编码(文件名1,文件base64编码串utf8;文件名2,文件base64编码串utf8);stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod(operationName = "mdMmsSend_uex")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdMmsSendUex(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "title", name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext
    );

    /**
     * 接收短信：sn软件序列号;pwd加密密码md5(sn+password).[优先使用本接口]
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mo(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号码,以英文逗号隔开;content内容,base64编码(zip文件base64编码串);stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdMmsSendF(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime
    );

    /**
     * 获取余额：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "GetBalance")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getBalance(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(operationName = "mdSmsSend_g")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdSmsSendG(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mt(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 设置高端发送：sn软件序列号;pwd序列号密码;gd参数1普通通道2高端通道;
     */
    @WebMethod(operationName = "SetGaoDuan")
    @WebResult(name = "double", targetNamespace = "http://tempuri.org/", partName = "Body")
    public double setGaoDuan(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "gd", name = "gd", targetNamespace = "http://tempuri.org/")
        java.lang.String gd
    );

    /**
     * 文件传输：sn软件序列号;pwd加密密码md5(sn+password);fname增值文件名;rrid第一个接口返回id;sort批次;total总次数;ftype类别1短信2彩信3语音4传真5邮件;content内容,base64编码.返回:rrid
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String fileMT(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "fname", name = "fname", targetNamespace = "http://tempuri.org/")
        java.lang.String fname,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid,
        @WebParam(partName = "sort", name = "sort", targetNamespace = "http://tempuri.org/")
        java.lang.String sort,
        @WebParam(partName = "total", name = "total", targetNamespace = "http://tempuri.org/")
        java.lang.String total,
        @WebParam(partName = "ftype", name = "ftype", targetNamespace = "http://tempuri.org/")
        java.lang.String ftype,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );

    /**
     * 发送变量短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字;bcode变量编码.返回:唯一标识
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String bianliang(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid,
        @WebParam(partName = "bcode", name = "bcode", targetNamespace = "http://tempuri.org/")
        java.lang.String bcode
    );

    /**
     * 发送短信：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容
     */
    @WebMethod(operationName = "SendSMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String sendSMS(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );

    /**
     * 通道测试：sn软件序列号;pwd序列号密码;mobile手机号列表，最多20个，以逗号,隔开
     */
    @WebMethod(operationName = "SMSTest")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String smsTest(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile
    );

    /**
     * 更改签名（网络版）：sn软件序列号;pwd序列号密码;sign企业签名(2-15个字符);subcode最长9位数字扩展码;comName企业全称
     */
    @WebMethod(operationName = "UDPSIGNEX")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String udpsignex(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "subcode", name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode,
        @WebParam(partName = "sign", name = "sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign,
        @WebParam(partName = "comName", name = "comName", targetNamespace = "http://tempuri.org/")
        java.lang.String comName
    );

    /**
     * 接收短信：sn软件序列号;pwd加密密码md5(sn+password);maxID：上次接收最大id
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mo2(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "maxID", name = "maxID", targetNamespace = "http://tempuri.org/")
        java.lang.String maxID
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdSmsSend(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 更改签名：sn软件序列号;pwd序列号密码;sign企业签名(2-15个字符)
     */
    @WebMethod(operationName = "UDPSIGN")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String udpsign(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "sign", name = "sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign
    );

    /**
     * 获取高端发送：sn软件序列号;pwd序列号密码;
     */
    @WebMethod(operationName = "GetGaoDuan")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getGaoDuan(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 获取软件序列号2参数：sn软件序列号;pwd序列号密码;
     */
    @WebMethod(operationName = "GetAllInfo2")
    @WebResult(name = "RegistryInfo2", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RegistryInfo2 getAllInfo2(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "ver", name = "ver", targetNamespace = "http://tempuri.org/")
        java.lang.String ver,
        @WebParam(partName = "oem", name = "oem", targetNamespace = "http://tempuri.org/")
        java.lang.String oem
    );

    /**
     * 回执：sn软件序列号;pwd加密密码md5(sn+password);maxid最大id
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String report2(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "maxid", name = "maxid", targetNamespace = "http://tempuri.org/")
        java.lang.String maxid,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 编解码：content中文内容;code编解码类型;type，0编码1解码
     */
    @WebMethod(operationName = "TestCode")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String testCode(
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "code", name = "code", targetNamespace = "http://tempuri.org/")
        java.lang.String code,
        @WebParam(partName = "type", name = "type", targetNamespace = "http://tempuri.org/")
        java.lang.String type
    );

    /**
     * 网络版接收短信utf-8编码：sn软件序列号;pwd序列号密码;subcode子号码。total_num为负数，表示操作失败
     */
    @WebMethod(operationName = "RECSMSEx_UTF8")
    @WebResult(name = "ArrayOfMOBody", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfMOBody recsmsExUTF8(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "subcode", name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod(operationName = "mdSmsSend_AES")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdSmsSendAES(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 发送短信（可扩展）：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容;subcode最长9位数字扩展码;rrid唯一标识,全数字
     */
    @WebMethod(operationName = "SendSMSEx_R")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String sendSMSExR(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "subcode", name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 接收短信：sn软件序列号;password加密密码md5(sn+password).
     */
    @WebMethod(operationName = "MongateCsGetSmsExEx")
    @WebResult(name = "ArrayOfString", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfString mongateCsGetSmsExEx(
        @WebParam(partName = "userId", name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    /**
     * 获取特服号：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "GetCode")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getCode(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 软件序列号注册：sn软件序列号;pwd序列号密码;province省;city城市;trade行业;entname企业名称;linkman联系人;phone联系电话;mobile移动电话;email邮件地址;fax传真;address地址;postcode邮政编码
     */
    @WebMethod(operationName = "Register")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String register(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "province", name = "province", targetNamespace = "http://tempuri.org/")
        java.lang.String province,
        @WebParam(partName = "city", name = "city", targetNamespace = "http://tempuri.org/")
        java.lang.String city,
        @WebParam(partName = "trade", name = "trade", targetNamespace = "http://tempuri.org/")
        java.lang.String trade,
        @WebParam(partName = "entname", name = "entname", targetNamespace = "http://tempuri.org/")
        java.lang.String entname,
        @WebParam(partName = "linkman", name = "linkman", targetNamespace = "http://tempuri.org/")
        java.lang.String linkman,
        @WebParam(partName = "phone", name = "phone", targetNamespace = "http://tempuri.org/")
        java.lang.String phone,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "email", name = "email", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(partName = "fax", name = "fax", targetNamespace = "http://tempuri.org/")
        java.lang.String fax,
        @WebParam(partName = "address", name = "address", targetNamespace = "http://tempuri.org/")
        java.lang.String address,
        @WebParam(partName = "postcode", name = "postcode", targetNamespace = "http://tempuri.org/")
        java.lang.String postcode,
        @WebParam(partName = "sign", name = "sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign
    );

    /**
     * 获取软件序列号子号码长度：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "GetFlag")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getFlag(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 接收短信utf-8编码：sn软件序列号;pwd序列号密码。total_num为负数，表示操作失败
     */
    @WebMethod(operationName = "RECSMS_UTF8")
    @WebResult(name = "ArrayOfMOBody", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfMOBody recsmsUTF8(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 传真发送：sn软件序列号;pwd加密密码md5(sn+password);title传真主题;mobile接收号码,以英文逗号隔开;content文件内容,base64编码(wav文件名,文件base64编码串);srcnumber发送号码;stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdFaxSend(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "title", name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "srcnumber", name = "srcnumber", targetNamespace = "http://tempuri.org/")
        java.lang.String srcnumber,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime
    );

    /**
     * 彩信发送：sn软件序列号;pwd加密密码md5(sn+password);title彩信主题;mobile手机号码,以英文逗号隔开;content内容,base64编码(文件名1,文件base64编码串;文件名2,文件base64编码串);stime定时时间2010-07-05 17:37:00.返回:rrid
     */
    @WebMethod(operationName = "mdMmsSend_ex")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String mdMmsSendEx(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "title", name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext
    );

    /**
     * 回执：sn软件序列号;pwd加密密码md5(sn+password);maxid最大id
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String report(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "maxid", name = "maxid", targetNamespace = "http://tempuri.org/")
        java.lang.String maxid
    );

    /**
     * 注销：sn软件序列号;pwd序列号密码
     */
    @WebMethod(operationName = "UnRegister")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String unRegister(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 获取软件序列号参数：sn软件序列号;pwd序列号密码;
     */
    @WebMethod(operationName = "GetAllInfo")
    @WebResult(name = "RegistryInfo", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RegistryInfo getAllInfo(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 网络版接收短信：sn软件序列号;pwd序列号密码;subcode子号码。total_num为负数，表示操作失败
     */
    @WebMethod(operationName = "RECSMSEx")
    @WebResult(name = "ArrayOfMOBody", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfMOBody recsmsEx(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "subcode", name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode
    );

    /**
     * 发送短信：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容;rrid唯一标识,全数字
     */
    @WebMethod(operationName = "SendSMS_R")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String sendSMSR(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );

    /**
     * 发送短信（可扩展）：sn软件序列号;pwd序列号密码;mobile手机号列表，以逗号,隔开;content发送内容;subcode最长9位数字扩展码
     */
    @WebMethod(operationName = "SendSMSEx")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String sendSMSEx(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "subcode", name = "subcode", targetNamespace = "http://tempuri.org/")
        java.lang.String subcode
    );

    /**
     * 充值：sn软件序列号;pwd序列号密码;cardno充值卡号;cardpwd充值卡密码
     */
    @WebMethod(operationName = "ChargUp")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String chargUp(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "cardno", name = "cardno", targetNamespace = "http://tempuri.org/")
        java.lang.String cardno,
        @WebParam(partName = "cardpwd", name = "cardpwd", targetNamespace = "http://tempuri.org/")
        java.lang.String cardpwd
    );

    /**
     * 获取信息ID：sn软件序列号;pwd加密密码md5(sn+password)
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String msgid(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    /**
     * 个性短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容,GB2312编码,以逗号,隔开;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字.返回:唯一标识
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String gxmt(
        @WebParam(partName = "sn", name = "sn", targetNamespace = "http://tempuri.org/")
        java.lang.String sn,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd,
        @WebParam(partName = "mobile", name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(partName = "ext", name = "ext", targetNamespace = "http://tempuri.org/")
        java.lang.String ext,
        @WebParam(partName = "stime", name = "stime", targetNamespace = "http://tempuri.org/")
        java.lang.String stime,
        @WebParam(partName = "rrid", name = "rrid", targetNamespace = "http://tempuri.org/")
        java.lang.String rrid
    );
}
